name: invite_only
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  # Provides widgets that allows you to create a readable responsive UI.
  # See https://pub.dev/packages/responsive_builder
  responsive_builder: ^0.1.5

  # International Phone Number Input For Flutter.
  # See https://pub.dev/packages/international_phone_input
  international_phone_input: ^1.0.3

  # A Flutter plugin to access and manage the device's contacts.
  # See https://pub.dev/packages/contacts_service
  contacts_service: ^0.3.10

  # This plugin provides a cross-platform (iOS, Android) API to request permissions and check their status.
  # See https://pub.dev/packages/permission_handler
  permission_handler: ^5.0.0+hotfix.3

  # A Flutter plugin to use the Firebase Core API, which enables connecting to multiple Firebase apps.
  # See https://pub.dev/packages/firebase_core
  firebase_core: ^0.4.4+3

  # A Flutter plugin to use the Google Analytics for Firebase API.
  # See https://pub.dev/packages/firebase_analytics
  firebase_analytics: ^5.0.11

  # A Flutter package that helps implement the BLoC pattern.
  # See https://pub.dev/packages/flutter_bloc
  flutter_bloc: ^3.2.0

  # Equatable overrides == and hashCode for you so you don't have to waste your time writing lots of boilerplate code.
  # See https://pub.dev/packages/equatable
  equatable: ^1.1.1

  # Scan identity documents such as South African ID Cards, ID Books and Driver's Licenses.
  # See https://pub.dev/packages/rsa_scan
  rsa_scan: ^0.0.1

  # Simple, fast generation of RFC4122 UUIDs.
  # See https://pub.dev/packages/uuid
  uuid: ^2.0.4

  # A simple API to format dates.
  # See https://pub.dev/packages/date_format
  date_format: ^1.0.8

  # A Flutter package providing the means to work Invite Only users.
  # See https://github.com/marcus-bornman/invite_only_users
  invite_only_auth:
      path: ../invite_only_auth

  # Access and manage identity document information for Invite Only users.
  # See https://github.com/marcus-bornman/invite_only_docs
  invite_only_docs:
    path: ../invite_only_docs

  # Manage or control access to Invite Only access-controlled Spaces
  # See https://github.com/marcus-bornman/invite_only_spaces
  invite_only_spaces:
    path: ../invite_only_spaces

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
