name: invite_only_repo
description: Access and manage users and access-controlled spaces remotely
version: 0.0.1
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Annotations for freezed. This package does nothing without freezed.
  # See https://pub.dev/packages/freezed_annotation
  freezed_annotation: ^0.7.1

  # A Flutter plugin to use the Firebase Core API, which enables connecting to multiple Firebase apps.
  # See https://pub.dev/packages/firebase_core
  firebase_core: ^0.4.4+3

  # A Flutter plugin to use the Firebase Authentication API.
  # See https://pub.dev/packages/firebase_auth
  firebase_auth: ^0.15.5+3

  # A Flutter plugin to use the Cloud Firestore API.
  # See https://pub.dev/packages/cloud_firestore
  cloud_firestore: ^0.13.4+2

  # Simple, fast generation of RFC4122 UUIDs.
  # See https://pub.dev/packages/uuid
  uuid: ^2.0.4

  # RxDart adds additional capabilities to Dart Streams and StreamControllers.
  # See https://pub.dev/packages/rxdart
  rxdart: ^0.24.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The build_runner package provides a concrete way of generating files using Dart code, outside of tools like pub.
  # See https://pub.dev/packages/build_runner
  build_runner: ^1.8.1

  # Welcome to Freezed, yet another code generator for unions/pattern-matching/copy.
  # See https://pub.dev/packages/freezed
  freezed: ^0.10.5

  # Provides Dart Build System builders for handling JSON.
  # See https://pub.dev/packages/json_serializable
  json_serializable: ^3.3.0

  # Mock library for Dart inspired by Mockito.
  # See https://pub.dev/packages/mockito
  mockito: ^4.1.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
