name: build-io-core

on:
  push:
    branches: [ master ]
    paths: 'invite_only_core/**'
  pull_request:
    branches: [ master ]
    paths: 'invite_only_core/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 13
      uses: actions/setup-java@v1
      with:
        java-version: 13
    - name: Build with Maven
      working-directory: invite_only_core
      run: mvn -B -DskipTests=true package --file pom.xml
